# 📊 NumPy: Numerical Python

NumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a rich set of high-level mathematical functions to operate on these arrays efficiently.

---

## 💡 Why Use NumPy?

- 🚀 High performance on large arrays and matrices
- 📐 Advanced mathematical and statistical operations
- 🔁 Easy broadcasting and vectorization
- 🔢 Great for machine learning, data analysis, and scientific computing

---

## 🧱 Key Features

- ndarray: N-dimensional array object
- Vectorized operations for speed and performance
- Tools for integrating with C/C++ and Fortran code
- Broadcasting, masking, indexing, reshaping, and more

---

## 🛠️ Installation

To install NumPy, use:

```bash
pip install numpy
````

Or with Anaconda:

```bash
conda install numpy
```

---

## 🔍 Basic Usage

```python
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4])
print(arr)

# Create a 2D array (matrix)
matrix = np.array([[1, 2], [3, 4]])

# Array of zeros and ones
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))

# Array with range
range_arr = np.arange(0, 10, 2)

# Reshaping
reshaped = np.reshape(arr, (2, 2))

# Element-wise operations
print(arr + 2)
print(arr * 3)
```

---

## 🧠 NumPy Array vs Python List

| Feature       | Python List      | NumPy Array       |
| ------------- | ---------------- | ----------------- |
| Speed         | Slower           | Faster            |
| Data Type     | Mixed types      | Same type only    |
| Functionality | Basic operations | Advanced math ops |
| Memory Usage  | Higher           | Lower             |

---

## 📚 Next Topics

* Array creation techniques
* Indexing and slicing
* Array math and broadcasting
* Linear algebra with NumPy
* Useful NumPy functions and tricks

---

NumPy is a cornerstone of the Python data science stack. Mastering it will make data manipulation and numerical analysis incredibly powerful and efficient.

```


In [2]:
import numpy as np

# create array using numpy
# create a 1d array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
#1d to 2d array
arr2= np.array([1,2,3,4,5])
arr2.reshape(1,5) 

array([[1, 2, 3, 4, 5]])

In [7]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of numpy array
arr = np.array([[1,2,3],[4,5,6]])

print("Array :\n", arr)
print("Shape:",arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array :
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [14]:
# Numpy vectorized operation
arr1= np.array([1,2,3,4,5])
arr2= np.array([10,20,30,40,50])

#Element wise addition
print("Addition; ", arr1+arr2)
#Element wise Subtraction
print("Subtraction; ", arr1-arr2)
#Element wise multiplication
print("multiplication; ", arr1 * arr2)
#Element wise Division
print("Division; ", arr1 / arr2)


Addition;  [11 22 33 44 55]
Subtraction;  [ -9 -18 -27 -36 -45]
multiplication;  [ 10  40  90 160 250]
Division;  [0.1 0.1 0.1 0.1 0.1]


In [16]:
# Universal function
arr = np.array([2,3,4,5,6])
#Square root 
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#Sine
print(np.log(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [20]:
# array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n ", arr)

Array : 
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
arr[0][0]

np.int64(1)

In [27]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [34]:
print(arr[0][0])
print(arr[0:2,2:])


1
[[3 4]
 [7 8]]


In [35]:
print(arr[1:3,1:3])

[[ 6  7]
 [10 11]]


In [36]:
# modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [37]:
arr[1:]= 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [39]:
# sttisticdal concepts - normalization
# to have a mean of 0 and standard deviation of 1
data = np.array((1,2,3,4,5)) 

# calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data :", normalized_data)

Normalized data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [41]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:",median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [47]:
# Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5) & (data<=8)]

array([6, 7, 8])